CREATE TABLE planes_mantenimiento (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE items_plan (
    id INT PRIMARY KEY AUTO_INCREMENT,
    plan_id INT NOT NULL,
    tarea VARCHAR(150) NOT NULL,
    intervalo_km INT NOT NULL,
    intervalo_meses INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (plan_id) REFERENCES planes_mantenimiento(id) ON DELETE CASCADE
);

CREATE TABLE motos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    anio INT,
    patente VARCHAR(20),
    km_actual INT NOT NULL DEFAULT 0,
    fecha_compra DATE,
    plan_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (plan_id) REFERENCES planes_mantenimiento(id) ON DELETE SET NULL
);

CREATE TABLE historial_mantenimiento (
    id INT PRIMARY KEY AUTO_INCREMENT,
    moto_id INT NOT NULL,
    item_plan_id INT NOT NULL,
    fecha_realizado DATE NOT NULL,
    km_realizado INT NOT NULL,
    observaciones TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (moto_id) REFERENCES motos(id) ON DELETE CASCADE,
    FOREIGN KEY (item_plan_id) REFERENCES items_plan(id) ON DELETE CASCADE
);